// A pool of creative AI/robot names for single-player and add-AI lobbies. The engine draws
// unused names from here when seating bots (see setBotCount). Kept server-only and
// dependency-free so both the engine and tests import it without a cycle.
//
// ~200 were brainstormed; these 50 are the survivors — short enough to render in a player
// chip, fun, and free of trademark baggage. Includes the user's seed examples (Harry the AI,
// Eunice the Robot, Sam Machine).
export const BOT_NAMES: string[] = [
  "Harry the AI",
  "Eunice the Robot",
  "Sam Machine",
  "Botstradamus",
  "Clankenstein",
  "Ada Byte",
  "Beep Boop",
  "Rusty Cogs",
  "Sir Compute",
  "Megabyte Meg",
  "Captain Circuit",
  "Gigabot",
  "Turing Tessa",
  "Data Dan",
  "Binary Betty",
  "Chip Hazard",
  "Voltaire",
  "Nano Nora",
  "Pixel Pete",
  "Subprime Sue",
  "Glitch",
  "Sparky",
  "Zappy",
  "Cyrus Cyborg",
  "Roboto",
  "Tin Lizzie",
  "Clanky",
  "Bolt",
  "Circuit Sally",
  "The Algorithm",
  "Dr. Droid",
  "Maxwell Machine",
  "Gizmo",
  "Servo",
  "Widget",
  "Cosmo Bot",
  "Buzz Logic",
  "Reggie Robot",
  "Cache Money",
  "Boolean Bob",
  "Faraday",
  "Mechano",
  "Professor Ohm",
  "Lady Logic",
  "Wattson",
  "Diode Dot",
  "Quincy Quantum",
  "Norma Node",
  "Tinny",
  "Mr. Mainframe",
];
